// Preset Templates
export default {
 // ═══════════════════ SCALPING ═══════════════════
    SCALP_AGGRESSIVE: { name: '⚡ Scalp Aggressive', description: 'Fast scalping with vol + OB Imbalance', conditions: [{ component: 'VOL_SPIKE_1M', operator: '>', value: 2.0, weight: 2 }, { component: 'OB_IMBALANCE', operator: 'ABS>', value: 0.3, weight: 1.5 }, { component: 'MICRO_VPIN', operator: '>', value: 0.5, weight: 1 }, { component: 'VOL_DURABILITY', operator: '>', value: 60, weight: 1 }], logic: 'WEIGHTED', minScore: 65, cooldown: 60 },
    SCALP_MOMENTUM: { name: '🏎️ Momentum Scalp', description: 'Momentum + VWAP Reversion', conditions: [{ component: 'SYN_VEL_5M', operator: 'ABS>', value: 5000, weight: 2 }, { component: 'MICRO_VWAP_DIST', operator: '<', value: 0.3, weight: 2 }, { component: 'BTC_OUTPERFORM', operator: '==', value: true, weight: 1 }], logic: 'AND', cooldown: 45 },
    SCALP_EFFICIENCY: { name: '📏 Efficient Move', description: 'Low friction price moves', conditions: [{ component: 'SYN_EFF_5M', operator: '>', value: 2.0, weight: 2 }, { component: 'SYN_CHAR', operator: 'CONTAINS', value: 'EFFORTLESS', weight: 2 }, { component: 'CIS_SCORE', operator: '>', value: 65, weight: 1 }], logic: 'AND', cooldown: 90 },

    // ═══════════════════ INSTITUTIONAL / WHALE ═══════════════════
    WHALE_TRACKER: { name: '🐋 Whale Tracker', description: 'Follow institutional flow + Walls', conditions: [{ component: 'SYN_SMART_DIV', operator: '>', value: 60, weight: 2 }, { component: 'VOL_FREQ_DIV', operator: '>', value: 1.5, weight: 1.5 }, { component: 'ALERT_WHALE', operator: '==', value: true, weight: 1.5 }], logic: 'AND', cooldown: 300 },
    SMART_MONEY: { name: '🧠 Smart Money', description: 'Institutional accumulation', conditions: [{ component: 'SYN_BIAS', operator: '==', value: 'ACCUMULATION', weight: 2 }, { component: 'SYN_SMART_DIV', operator: '>', value: 65, weight: 1.5 }, { component: 'MICRO_KYLE', operator: '<', value: 0.5, weight: 1 }, { component: 'VOL_SPIKE_15M', operator: '>', value: 1.2, weight: 1 }], logic: 'WEIGHTED', minScore: 65, cooldown: 300, biasLogic: 'LONG' },
    DISTRIBUTION: { name: '📤 Distribution', description: 'Smart money selling', conditions: [{ component: 'SYN_BIAS', operator: '==', value: 'DISTRIBUTION', weight: 2 }, { component: 'SYN_SMART_DIV', operator: '>', value: 65, weight: 1.5 }, { component: 'PRICE_CHANGE_1H', operator: '<', value: -0.5, weight: 1 }], logic: 'AND', cooldown: 300, biasLogic: 'SHORT' },

    // ═══════════════════ DERIVATIVES ═══════════════════
    FUNDING_ARB: { name: '💰 Funding Arb', description: 'Extreme funding contrarian', conditions: [{ component: 'FUNDING_ZSCORE', operator: 'ABS>', value: 2.5, weight: 2 }, { component: 'FUNDING_APY', operator: 'ABS>', value: 30, weight: 1.5 }], logic: 'AND', cooldown: 600, biasLogic: 'CONTRARIAN' },
    OI_SURGE: { name: '📈 OI Surge', description: 'New positions opening', conditions: [{ component: 'OI_CHANGE_15M', operator: '>', value: 2.5, weight: 2 }, { component: 'OI_CHANGE_1H', operator: '>', value: 4.0, weight: 1.5 }, { component: 'VOL_SPIKE_15M', operator: '>', value: 1.5, weight: 1 }], logic: 'AND', cooldown: 300 },
    OI_FLUSH: { name: '📉 OI Flush', description: 'Positions closing rapidly', conditions: [{ component: 'OI_CHANGE_15M', operator: '<', value: -2.0, weight: 2 }, { component: 'LIQ_RATE', operator: '>', value: 2.0, weight: 1.5 }, { component: 'VOL_SPIKE_5M', operator: '>', value: 2.0, weight: 1 }], logic: 'AND', cooldown: 180, biasLogic: 'CONTRARIAN' },
    LSR_EXTREME: { name: '📐 LSR Extreme', description: 'Crowded positioning', conditions: [{ component: 'LSR_ZSCORE', operator: 'ABS>', value: 2.0, weight: 2 }, { component: 'LSR_PERCENTILE', operator: '>', value: 90, weight: 1.5 }], logic: 'AND', cooldown: 600, biasLogic: 'CONTRARIAN' },

    // ═══════════════════ BREAKOUT / MOMENTUM ═══════════════════
    BREAKOUT: { name: '🚀 Breakout', description: 'Volume + OI + OB imbalance', conditions: [{ component: 'VOL_SPIKE_5M', operator: '>', value: 1.8, weight: 2 }, { component: 'OB_IMBALANCE', operator: 'ABS>', value: 0.4, weight: 2 }, { component: 'PRICE_CHANGE_5M', operator: 'ABS>', value: 1.0, weight: 1.5 }], logic: 'WEIGHTED', minScore: 70, cooldown: 180 },
    SQUEEZE_BREAK: { name: '💥 Squeeze Break', description: 'Vol expansion from consolidation', conditions: [{ component: 'VOL_REGIME', operator: '==', value: 'LOW_VOL', weight: 1 }, { component: 'VOL_SPIKE_5M', operator: '>', value: 2.5, weight: 2 }, { component: 'BTC_BETA', operator: '>', value: 1.2, weight: 1 }], logic: 'AND', cooldown: 180 },
    TREND_CONTINUATION: { name: '📈 Trend Cont', description: 'Ride trend with BTC strength', conditions: [{ component: 'REGIME_CURRENT', operator: 'CONTAINS', value: 'TRENDING', weight: 2 }, { component: 'BTC_OUTPERFORM', operator: '==', value: true, weight: 2 }, { component: 'SYN_EFF_15M', operator: '>', value: 1.3, weight: 1 }], logic: 'AND', cooldown: 300 },

    // ═══════════════════ REVERSAL / MEAN REVERSION ═══════════════════
    REVERSAL: { name: '🔄 Reversal', description: 'Contrarian divergence', conditions: [{ component: 'LSR_ZSCORE', operator: 'ABS>', value: 2.0, weight: 2 }, { component: 'BTC_DIVERGENCE', operator: '==', value: true, weight: 2 }, { component: 'ENH_CVD_DIV', operator: '==', value: true, weight: 2 }], logic: 'OR', cooldown: 600, biasLogic: 'CONTRARIAN' },
    OVERSOLD_BOUNCE: { name: '📉 Oversold Bounce', description: 'Mean reversion long', conditions: [{ component: 'PRICE_FROM_HIGH', operator: '<', value: -8, weight: 2 }, { component: 'LSR_RATIO', operator: '<', value: 0.8, weight: 1.5 }, { component: 'VOL_SPIKE_15M', operator: '>', value: 1.5, weight: 1 }], logic: 'AND', cooldown: 300, biasLogic: 'LONG' },
    OVERBOUGHT_FADE: { name: '📈 Overbought Fade', description: 'Mean reversion short', conditions: [{ component: 'PRICE_FROM_LOW', operator: '>', value: 8, weight: 2 }, { component: 'LSR_RATIO', operator: '>', value: 1.3, weight: 1.5 }, { component: 'FUNDING_RATE', operator: '>', value: 0.0003, weight: 1 }], logic: 'AND', cooldown: 300, biasLogic: 'SHORT' },

    // ═══════════════════ LIQUIDATION ═══════════════════
    LIQ_PLAY: { name: '💥 Liquidation Cascade', description: 'Trade liquidation cascade', conditions: [{ component: 'LIQ_RATE', operator: '>', value: 3.0, weight: 2 }, { component: 'VOL_SPIKE_1M', operator: '>', value: 3.0, weight: 1.5 }], logic: 'AND', cooldown: 120, biasLogic: 'CONTRARIAN' },
    LIQ_LONG_SQUEEZE: { name: '🔻 Long Squeeze', description: 'Longs getting liquidated', conditions: [{ component: 'LIQ_DOMINANT', operator: '==', value: 'LONG LIQ', weight: 2 }, { component: 'LIQ_RATE', operator: '>', value: 2.0, weight: 1.5 }, { component: 'PRICE_CHANGE_5M', operator: '<', value: -1.0, weight: 1 }], logic: 'AND', cooldown: 120, biasLogic: 'CONTRARIAN' },
    LIQ_SHORT_SQUEEZE: { name: '🔺 Short Squeeze', description: 'Shorts getting rekt', conditions: [{ component: 'LIQ_DOMINANT', operator: '==', value: 'SHORT LIQ', weight: 2 }, { component: 'LIQ_RATE', operator: '>', value: 2.0, weight: 1.5 }, { component: 'PRICE_CHANGE_5M', operator: '>', value: 1.0, weight: 1 }], logic: 'AND', cooldown: 120, biasLogic: 'LONG' },
    LIQ_REVERSAL: { name: '🧹 Liq Sweep Reversal', description: 'Sweep > Reversal (Stop hunting)', conditions: [{ component: 'LIQ_SWEEP', operator: '>', value: 0.5, weight: 2 }, { component: 'LSR_ZSCORE', operator: 'ABS>', value: 2.0, weight: 1.5 }], logic: 'AND', cooldown: 300, biasLogic: 'CONTRARIAN' },

    // ═══════════════════ MICROSTRUCTURE ═══════════════════
    TOXIC_FLOW: { name: '☠️ Toxic Flow', description: 'Informed trading detected', conditions: [{ component: 'MICRO_VPIN', operator: '>', value: 0.7, weight: 2 }, { component: 'MICRO_TFI', operator: '>', value: 0.6, weight: 1.5 }, { component: 'VOL_SPIKE_5M', operator: '>', value: 1.5, weight: 1 }], logic: 'AND', cooldown: 180 },
    BOOK_IMBALANCE: { name: '📚 Book Imbalance', description: 'Order book pressure', conditions: [{ component: 'OB_IMBALANCE', operator: 'ABS>', value: 0.3, weight: 2 }, { component: 'OB_DEPTH_RATIO', operator: '>', value: 1.5, weight: 1.5 }, { component: 'MICRO_OFI', operator: '>', value: 60, weight: 1 }], logic: 'WEIGHTED', minScore: 60, cooldown: 120 },
    WALL_BREAK: { name: '🧱 Wall Break', description: 'Breaking order wall', conditions: [{ component: 'OB_WALL_DETECTED', operator: '==', value: true, weight: 1 }, { component: 'VOL_SPIKE_1M', operator: '>', value: 2.5, weight: 2 }, { component: 'PRICE_CHANGE_1M', operator: 'ABS>', value: 0.3, weight: 1.5 }], logic: 'AND', cooldown: 90 },

    // ═══════════════════ CONVERGENCE / HIGH CONVICTION ═══════════════════
    CONVERGENCE: { name: '🎯 Convergence', description: 'Multiple signals aligning', conditions: [{ component: 'MASTER_SCORE', operator: '>=', value: 70, weight: 2 }, { component: 'CIS_SCORE', operator: '>=', value: 60, weight: 1.5 }, { component: 'DASH_TOTAL', operator: '>=', value: 65, weight: 1 }, { component: 'ALERT_CONV', operator: '==', value: true, weight: 1.5 }], logic: 'WEIGHTED', minScore: 70, cooldown: 300 },
    FULL_ALIGNMENT: { name: '✨ Full Alignment', description: 'Everything agrees', conditions: [{ component: 'MASTER_MTF', operator: '==', value: true, weight: 2 }, { component: 'MASTER_CONFIRMS', operator: '>=', value: 5, weight: 2 }, { component: 'SYN_CHAR', operator: 'CONTAINS', value: 'EFFORTLESS', weight: 1.5 }, { component: 'CIS_SCORE', operator: '>', value: 65, weight: 1 }], logic: 'AND', cooldown: 300 },
    HIGH_CONFIDENCE: { name: '💪 High Confidence', description: 'Strong conviction setup', conditions: [{ component: 'MASTER_CONFIDENCE', operator: '>=', value: 80, weight: 2 }, { component: 'MASTER_SCORE', operator: '>=', value: 75, weight: 2 }, { component: 'STRAT_CORWIN', operator: '<', value: 0.1, weight: 1 }], logic: 'AND', cooldown: 300 },

    // ═══════════════════ BTC CORRELATION ═══════════════════
    BTC_FOLLOW: { name: '₿ BTC Follower', description: 'Trade alts that follow BTC', conditions: [{ component: 'BTC_FOLLOWS', operator: '==', value: true, weight: 2 }, { component: 'BTC_CHANGE_5M', operator: 'ABS>', value: 0.3, weight: 1.5 }, { component: 'MASTER_SCORE', operator: '>=', value: 60, weight: 1 }], logic: 'AND', cooldown: 180 },
    BTC_DIVERGE: { name: '↔️ BTC Divergence', description: 'Alts diverging from BTC', conditions: [{ component: 'BTC_DIVERGES', operator: '==', value: true, weight: 2 }, { component: 'BTC_OUTPERFORM', operator: '==', value: true, weight: 1.5 }, { component: 'VOL_SPIKE_5M', operator: '>', value: 1.5, weight: 1 }], logic: 'AND', cooldown: 300 },
    BTC_BETA_PLAY: { name: '📊 High Beta', description: 'High beta alts when BTC moves', conditions: [{ component: 'BTC_BETA', operator: '>', value: 1.5, weight: 2 }, { component: 'BTC_CHANGE_5M', operator: 'ABS>', value: 0.5, weight: 2 }, { component: 'BTC_FOLLOWS', operator: '==', value: true, weight: 1 }], logic: 'AND', cooldown: 180 },
    BTC_DIP_BUY: { name: '₿ BTC Dip Buy', description: 'Buy alts when BTC dips', conditions: [{ component: 'BTC_CHANGE_15M', operator: '<', value: -1.0, weight: 2 }, { component: 'BTC_FOLLOWS', operator: '==', value: true, weight: 1.5 }, { component: 'MASTER_ACTION', operator: '==', value: 'BUY', weight: 1 }], logic: 'AND', cooldown: 300, biasLogic: 'LONG' },

    // ═══════════════════ SPECIAL CONDITIONS ═══════════════════
    DISCOUNT_HUNTER: { name: '🏷️ Discount Hunter', description: 'Buy significant pullbacks', conditions: [{ component: 'PRICE_FROM_HIGH', operator: '<', value: -10, weight: 2 }, { component: 'ALERT_DISCOUNT', operator: '==', value: true, weight: 1 }, { component: 'SYN_BIAS', operator: '==', value: 'ACCUMULATION', weight: 1.5 }], logic: 'AND', cooldown: 600, biasLogic: 'LONG' },
    VOLATILITY_PLAY: { name: '🌋 Vol Spike', description: 'High volatility opportunities', conditions: [{ component: 'VOL_REGIME', operator: '==', value: 'HIGH_VOL', weight: 2 }, { component: 'VOL_SPIKE_5M', operator: '>', value: 2.0, weight: 1.5 }, { component: 'MASTER_CONFIDENCE', operator: '>=', value: 65, weight: 1 }], logic: 'AND', cooldown: 120 },
    QUIET_ACCUMULATION: { name: '🤫 Quiet Accum', description: 'Stealth accumulation', conditions: [{ component: 'VOL_REGIME', operator: '==', value: 'LOW_VOL', weight: 1 }, { component: 'OI_CHANGE_1H', operator: '>', value: 2.0, weight: 2 }, { component: 'SYN_BIAS', operator: '==', value: 'ACCUMULATION', weight: 2 }], logic: 'AND', cooldown: 600, biasLogic: 'LONG' },

    // ═══════════════════ ADVANCED STRATEGIES (from Strategy Tab) ═══════════════════
    STRAT_FLASH: { name: '⚡ Flash Pump Detector', description: 'Mendeteksi koin SEBELUM pompa signifikan. Masuk di 30 detik pertama pergerakan impulsif. Lev: 5-10x, Hold: 5m-30m', conditions: [{ component: 'VOL_SPIKE_1M', operator: '>', value: 1.5, weight: 2 }, { component: 'MASTER_SCORE', operator: '>', value: 52, weight: 1.5 }, { component: 'SYN_FLOW_5M', operator: '>', value: 5000, weight: 1 }], logic: 'AND', cooldown: 300 },
    STRAT_GAMMA: { name: '🎲 Gamma Exposure', description: 'Mendeteksi Gamma Squeeze. Korelasi OI dan Volatilitas sebagai proxy hedging dealer options. Lev: 5-10x, Hold: 1h-4h', conditions: [{ component: 'OI_CHANGE_1H', operator: 'ABS>', value: 5.0, weight: 2 }, { component: 'OI_NET_SCORE', operator: 'ABS>', value: 15, weight: 1.5 }], logic: 'OR', cooldown: 600 },
    STRAT_CLUSTER: { name: '🎯 Volume Cluster', description: 'Zona harga institusi akumulasi diam-diam (Volume Profile Nodes). High Vol + Low Price Change. Lev: 3-5x, Hold: 4h-12h', conditions: [{ component: 'VOL_SPIKE_1H', operator: '>', value: 1.5, weight: 2 }, { component: 'PRICE_CHANGE_1H', operator: '>', value: -0.5, weight: 1.5 }, { component: 'PRICE_CHANGE_1H', operator: '<', value: 0.5, weight: 1.5 }], logic: 'AND', cooldown: 600, biasLogic: 'LONG' },
    STRAT_TAPE: { name: '📜 Tape Reading', description: 'Agresivitas Tape (Trade Feed). Urutan order beli/jual agresif. Lev: 10-20x, Hold: 1m-5m', conditions: [{ component: 'SYN_AGGR', operator: '==', value: 'INSTITUTIONAL', weight: 2 }, { component: 'MICRO_VPIN', operator: '>', value: 0.55, weight: 1.5 }], logic: 'AND', cooldown: 120 },
    STRAT_ANOMALY: { name: '⚠️ Statistical Anomaly', description: 'Pergerakan 3-Sigma menyimpang statistik. Mean reversion atau breakout ekstrim. Lev: 2-5x, Hold: 1h-6h', conditions: [{ component: 'LSR_ZSCORE', operator: 'ABS>', value: 3.0, weight: 2 }, { component: 'OI_NET_SCORE', operator: 'ABS>', value: 20, weight: 2 }], logic: 'OR', cooldown: 600 },
    STRAT_COMPOSITE: { name: '👑 Composite Alpha (God Signal)', description: 'Framework paling advanced: Bobot adaptif, Net Flow massif, Institutional Footprint, Konfluensi MTF. Lev: 5-15x, Hold: 15m-1h', conditions: [{ component: 'MASTER_SCORE', operator: '>', value: 67, weight: 2 }, { component: 'SYN_FLOW_15M', operator: 'ABS>', value: 30000, weight: 2 }, { component: 'MASTER_MTF', operator: '==', value: true, weight: 2 }, { component: 'ENH_INST', operator: '>', value: 0.6, weight: 1.5 }, { component: 'GUARD_ALLOWED', operator: '==', value: true, weight: 1 }], logic: 'AND', cooldown: 600 },
    STRAT_BLITZ: { name: '⚡ Institutional Blitz', description: 'Konfluensi sempurna: Net Flow besar, EFFORTLESS MOVE, CVD konfirmasi. Setup sniper paling murni. Lev: 10-25x, Hold: 2m-10m', conditions: [{ component: 'SYN_FLOW_15M', operator: 'ABS>', value: 22500, weight: 2 }, { component: 'SYN_CHAR', operator: 'CONTAINS', value: 'EFFORTLESS', weight: 2 }, { component: 'SYN_AGGR', operator: '==', value: 'INSTITUTIONAL', weight: 1.5 }, { component: 'GUARD_STATUS', operator: '==', value: 'ALLOW', weight: 1 }], logic: 'AND', cooldown: 300 },
    STRAT_MTF_PRO: { name: '📡 MTF Confluence Pro', description: 'Trigger saat 1M, 5M, 15M, 1H sama arah dengan Momentum Quality tinggi. Lev: 3-10x, Hold: 1h-4h', conditions: [{ component: 'MASTER_MTF', operator: '==', value: true, weight: 3 }, { component: 'ENH_MOM_QUAL', operator: '>', value: 0.4, weight: 2 }], logic: 'AND', cooldown: 600 },
    STRAT_BREAKOUT: { name: '💥 Institutional Breakout', description: 'Ledakan harga divalidasi VPIN tinggi, Book Resilience kuat. Menghindari False Breakout. Lev: 10x, Hold: 15m-1h', conditions: [{ component: 'MICRO_VPIN', operator: '>', value: 0.45, weight: 2 }, { component: 'SYN_FLOW_15M', operator: 'ABS>', value: 15000, weight: 2 }, { component: 'ENH_BOOK_RES', operator: '>', value: 0.5, weight: 1.5 }], logic: 'AND', cooldown: 300 },
    STRAT_ALPHA: { name: '🏹 Independent Alpha', description: 'Koin Outlier bergerak independen (BTC Decorrelated). Efektif saat BTC sideways. Lev: 5x, Hold: 4h-12h', conditions: [{ component: 'BTC_BETA', operator: '<', value: 0.4, weight: 2 }, { component: 'MASTER_SCORE', operator: '>', value: 52, weight: 1.5 }], logic: 'AND', cooldown: 600 },
    STRAT_FLOW: { name: '🌊 Net Flow Directional', description: 'Murni mengikuti arus modal dengan konfirmasi CVD. Trade sesuai Dominant Capital Bias. Lev: 3-10x, Hold: 1h-4h', conditions: [{ component: 'SYN_FLOW_15M', operator: 'ABS>', value: 15000, weight: 2 }, { component: 'SYN_BIAS', operator: '!=', value: 'NEUTRAL', weight: 1.5 }], logic: 'AND', cooldown: 300 },
    STRAT_SMART_MONEY: { name: '🏦 Smart Money Divergence', description: 'Volume per koin meledak TAPI frekuensi transaksi stabil/turun (Large orders hidden). Lev: 5x, Hold: 4h-24h', conditions: [{ component: 'ENH_INST', operator: '>', value: 0.4, weight: 2 }, { component: 'MASTER_ACTION', operator: '!=', value: 'WAIT', weight: 1 }], logic: 'AND', cooldown: 600 },
    STRAT_WHALE: { name: '🐋 Whale Shadow Tracker', description: 'Membuntuti Whale-Pace dengan Institutional Footprint Score + Amihud Ratio rendah. Lev: 10x, Hold: 30m-1h', conditions: [{ component: 'ENH_INST', operator: '>', value: 0.7, weight: 2 }, { component: 'SYN_VEL_15M', operator: '>', value: 3000, weight: 1.5 }], logic: 'AND', cooldown: 300 },
    STRAT_DIVERGE: { name: '📈 Price-Flow Divergence', description: 'Harga turun tapi Net Flow naik tajam (Hidden Accumulation) atau sebaliknya. Lev: 5-10x, Hold: 1h-2h', conditions: [{ component: 'PRICE_CHANGE_24H', operator: '<', value: -2, weight: 1 }, { component: 'SYN_FLOW_15M', operator: '>', value: 20000, weight: 2 }], logic: 'AND', cooldown: 300, biasLogic: 'LONG' },
    STRAT_ICEBERG: { name: '🧊 Iceberg Detection', description: 'Pesanan raksasa dipecah-pecah di order book (OFI dan Lambda). Lev: 10x, Hold: 30m-1h', conditions: [{ component: 'OB_IMBALANCE', operator: 'ABS>', value: 0.5, weight: 2 }, { component: 'ENH_AMIHUD', operator: '>', value: 0.3, weight: 1.5 }, { component: 'ENH_INST', operator: '>', value: 0.3, weight: 1 }], logic: 'AND', cooldown: 300 },
    STRAT_ABSORB: { name: '🧲 Whale Absorption', description: 'Volume meledak tapi harga tidak bergerak (Paku) + Book Resilience tinggi. Paus menyerap ritel. Lev: 10x, Hold: 1h-3h', conditions: [{ component: 'SYN_CHAR', operator: 'CONTAINS', value: 'ABSORPTION', weight: 2 }, { component: 'SYN_FLOW_15M', operator: 'ABS>', value: 15000, weight: 1.5 }, { component: 'ENH_BOOK_RES', operator: '>', value: 0.5, weight: 1.5 }], logic: 'AND', cooldown: 300 },
    STRAT_SWEEP: { name: '🧹 Liquidity Sweep', description: 'Pembersihan likuiditas (wick panjang) sebelum harga berbalik. Snipe di atas/bawah konsolidasi. Lev: 20x, Hold: 5m-15m', conditions: [{ component: 'LSR_ZSCORE', operator: 'ABS>', value: 2.5, weight: 2 }, { component: 'LIQ_RATE', operator: '>', value: 2.0, weight: 1.5 }], logic: 'AND', cooldown: 180 },
    STRAT_TRAP: { name: '🚨 Liquidation Reversal', description: 'Titik jenuh likuidasi ritel (Absorption). Masuk saat Washout dengan CVD berlawanan. Lev: 10x, Hold: 1h-2h', conditions: [{ component: 'SYN_CHAR', operator: 'CONTAINS', value: 'ABSORPTION', weight: 2 }, { component: 'LSR_ZSCORE', operator: 'ABS>', value: 2.0, weight: 1.5 }], logic: 'OR', cooldown: 300, biasLogic: 'CONTRARIAN' },
    STRAT_VOL: { name: '🌩️ Volatility Breakout', description: 'Transisi konsolidasi sepi ke ledakan volatilitas + Volume Spike + Momentum Quality. Lev: 3-5x, Hold: 4h-8h', conditions: [{ component: 'ENH_MOM_QUAL', operator: '>', value: 0.4, weight: 2 }, { component: 'VOL_SPIKE_15M', operator: '>', value: 1.5, weight: 1.5 }], logic: 'AND', cooldown: 600 },
    STRAT_EFFICIENCY: { name: '🧬 Efficiency-Momentum', description: 'Efficiency, momentum quality, dan pressure acceleration. Harga bergerak efisien dengan momentum bersih. Lev: 5-10x, Hold: 30m-2h', conditions: [{ component: 'SYN_EFF_15M', operator: '>', value: 0.8, weight: 2 }, { component: 'SYN_VEL_15M', operator: '>', value: 3000, weight: 1.5 }, { component: 'ENH_MOM_QUAL', operator: '>', value: 0.5, weight: 1.5 }], logic: 'AND', cooldown: 300 },
    STRAT_SWING: { name: '🏛️ Swing Accumulation', description: 'Aset sedang diakumulasi institusi dengan Institutional Footprint tinggi. Hold 1-3 hari mengikuti uang pintar. Lev: 3-5x', conditions: [{ component: 'MASTER_SCORE', operator: '>', value: 52, weight: 1 }, { component: 'SYN_FLOW_15M', operator: '>', value: 4500, weight: 1.5 }, { component: 'ENH_INST', operator: '>', value: 0.5, weight: 2 }], logic: 'AND', cooldown: 900, biasLogic: 'LONG' },
    STRAT_BASIS: { name: '💎 Delta-Neutral Basis', description: 'Selisih harga Futures vs Spot + funding raksasa. Resiko harga nol, murni bunga inap. Lev: 1x, Hold: 7d-30d', conditions: [{ component: 'FUNDING_RATE', operator: 'ABS>', value: 0.001, weight: 2 }], logic: 'AND', cooldown: 3600, biasLogic: 'CONTRARIAN' },
    STRAT_WALLS: { name: '🧱 Wall Defender', description: 'Harga tertahan tembok pesanan raksasa. Strategi rebound dengan resiko rendah. Lev: 5-12x, Hold: 1h-4h', conditions: [{ component: 'OB_WALL_DETECTED', operator: '==', value: true, weight: 2 }], logic: 'AND', cooldown: 300 },
    STRAT_FISHER: { name: '🌊 Liquidity Fisher', description: 'Titik jenuh pembalikan saat likuiditas kosong dan menyentuh tembok institusi. Pantulan ekstrim. Lev: 5-10x, Hold: 15m-45m', conditions: [{ component: 'OB_SPREAD', operator: '>', value: 20, weight: 2 }, { component: 'OB_DEPTH_RATIO', operator: '>', value: 2, weight: 1.5 }], logic: 'AND', cooldown: 300, biasLogic: 'LONG' },
    STRAT_VOID: { name: '🕳️ Order Book Vacuum', description: 'Lubang likuiditas antara harga saat ini dengan tembok berikutnya. Pergerakan kilat zona kosong. Lev: 20x, Hold: 5m-10m', conditions: [{ component: 'OB_SPREAD', operator: '>', value: 6.0, weight: 2 }], logic: 'AND', cooldown: 120 },
    STRAT_SENTIMENT: { name: '⚖️ Sentiment Contrarian', description: 'Posisi berlawanan dengan kerumunan ritel optimis/pesimis. Anti-herd entry. Lev: 10x, Hold: 1h-4h', conditions: [{ component: 'LSR_ZSCORE', operator: 'ABS>', value: 1.8, weight: 2 }], logic: 'AND', cooldown: 600, biasLogic: 'CONTRARIAN' },
    STRAT_MEAN_REV: { name: '🔄 Mean Reversion', description: 'Titik jenuh harga jauh dari VWAP + Net Flow stabil/reverse. Snap-back ke rata-rata. Lev: 5-10x, Hold: 30m-1h', conditions: [{ component: 'PRICE_FROM_HIGH', operator: 'ABS>', value: 3, weight: 2 }], logic: 'AND', cooldown: 300, biasLogic: 'CONTRARIAN' },
    STRAT_PATIENCE: { name: '⌛ Patience Sniper', description: 'Setup Perfect Storm. Semua enhanced signals alignment: MTF Pro, Net Flow, Inst Footprint, Mom Quality, Book Res. Lev: 2-5x, Hold: 12h-48h', conditions: [{ component: 'MASTER_SCORE', operator: '>', value: 72, weight: 2 }, { component: 'SYN_FLOW_15M', operator: 'ABS>', value: 45000, weight: 2 }, { component: 'ENH_INST', operator: '>', value: 0.7, weight: 2 }, { component: 'ENH_MOM_QUAL', operator: '>', value: 0.6, weight: 1.5 }, { component: 'ENH_BOOK_RES', operator: '>', value: 0.6, weight: 1.5 }, { component: 'GUARD_ALLOWED', operator: '==', value: true, weight: 1 }], logic: 'AND', cooldown: 900 },
    STRAT_IGNITION: { name: '📈 Momentum Ignition', description: 'Awal trend sehat: OI naik tajam + Net Capital Inflow + Pressure Acceleration + Momentum Quality. Lev: 3x, Hold: 3d-7d', conditions: [{ component: 'MASTER_SCORE', operator: '>', value: 52, weight: 1 }, { component: 'SYN_FLOW_15M', operator: '>', value: 12000, weight: 1.5 }, { component: 'ENH_MOM_QUAL', operator: '>', value: 0.5, weight: 2 }], logic: 'AND', cooldown: 600 },
    STRAT_FUNDING: { name: '💸 Funding Rate Arb', description: 'Selisih ekstrim Funding Rate vs Premium Index. Long saat funding negatif, Short saat positif tinggi. Lev: 1-3x, Hold: 8h-24h', conditions: [{ component: 'FUNDING_RATE', operator: 'ABS>', value: 0.0008, weight: 2 }], logic: 'AND', cooldown: 1800, biasLogic: 'CONTRARIAN' },
    STRAT_SAFETY: { name: '🛡️ Toxic Flow Filter', description: 'Sistem pelindung modal. Identifikasi koin dimanipulasi robot HFT. JANGAN TRADE. Risk Guard.', conditions: [{ component: 'MICRO_VPIN', operator: '>', value: 0.8, weight: 2 }], logic: 'AND', cooldown: 60, biasLogic: 'STAY_AWAY', maxPositions: 0 }

};
