// Auto-generated file - do not edit by hand
export default {
    // ═══════════════════ confluence ═══════════════════
    aligned: { category: 'CONFLUENCE', name: 'Confluence aligned', icon: '✔️', path: 'signals.confluenceSignals.aligned', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'YES', valueType: 'select', options: ['YES', 'NO'], description: 'Indicates if multi-timeframe signals are aligned' },
    conflicting: { category: 'CONFLUENCE', name: 'Confluence conflicting', icon: '❌', path: 'signals.confluenceSignals.conflicting', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'YES', valueType: 'select', options: ['YES', 'NO'], description: 'Indicates if multi-timeframe signals are conflicting' },
    confluenceScore: { category: 'CONFLUENCE', name: 'Confluence confluenceScore', icon: '💯', path: 'signals.confluenceSignals.confluenceScore', operators: ['>', '<'], defaultThreshold: 50, description: 'Overall confluence score calculated from alignment across timeframes' },
    quality: { category: 'CONFLUENCE', name: 'Confluence quality', icon: '🏷️', path: 'signals.confluenceSignals.quality', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'LOW', valueType: 'select', options: ['LOW', 'HIGH'], description: 'Categorical label of confluence quality' },
    entryRecommendation: { category: 'CONFLUENCE', name: 'Confluence entryRecommendation', icon: '💡', path: 'signals.confluenceSignals.entryRecommendation', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['LONG', 'SHORT', 'NEUTRAL', 'WAIT'], description: 'Recommended trading action based on confluence' },
    direction5m: { category: 'CONFLUENCE', name: 'Confluence direction5m', icon: '⏱️', path: 'signals.confluenceSignals.direction5m', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['LONG', 'SHORT', 'NEUTRAL', 'WAIT'], description: 'Dominant direction on the 5-minute timeframe' },
    direction15m: { category: 'CONFLUENCE', name: 'Confluence direction15m', icon: '⏱️', path: 'signals.confluenceSignals.direction15m', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['LONG', 'SHORT', 'NEUTRAL', 'WAIT'], description: 'Dominant direction on the 15-minute timeframe' },
    score5m: { category: 'CONFLUENCE', name: 'Confluence score5m', icon: '📊', path: 'signals.confluenceSignals.score5m', operators: ['>', '<'], defaultThreshold: 50, description: 'Aggregate confidence score on the 5-minute timeframe' },
    score15m: { category: 'CONFLUENCE', name: 'Confluence score15m', icon: '📊', path: 'signals.confluenceSignals.score15m', operators: ['>', '<'], defaultThreshold: 50, description: 'Aggregate confidence score on the 15-minute timeframe' },
    confidence5m: { category: 'CONFLUENCE', name: 'Confluence confidence5m', icon: '🎯', path: 'signals.confluenceSignals.confidence5m', operators: ['>', '<'], defaultThreshold: 50, description: 'Confidence level of the 5-minute signal' },
    confidence15m: { category: 'CONFLUENCE', name: 'Confluence confidence15m', icon: '🎯', path: 'signals.confluenceSignals.confidence15m', operators: ['>', '<'], defaultThreshold: 50, description: 'Confidence level of the 15-minute signal' },
};
