// Auto-generated file - do not edit by hand
export default {

    orderFlow_flowDirection: { category: 'ANALYTICSSUMMARY', name: 'orderFlow_flowDirection', icon: '🌊', path: 'analyticsSummary.orderFlow_flowDirection', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['NEUTRAL', 'LONG', 'SHORT'], description: 'Direction of order flow (LONG/SHORT/NEUTRAL)' },

    confluenceStrength: { category: 'ANALYTICSSUMMARY', name: 'confluenceStrength', icon: '🔗', path: 'analyticsSummary.mtfAnalysis_confluenceStrength', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NONE', valueType: 'select', options: ['STRONG', 'MODERATE', 'WEAK', 'NONE'], description: 'Strength of multi-timeframe signal confluence' },
    confluenceDirection: { category: 'ANALYTICSSUMMARY', name: 'confluenceDirection', icon: '🧭', path: 'analyticsSummary.mtfAnalysis_confluenceDirection', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'MIXED', valueType: 'select', options: ['BULLISH', 'BEARISH', 'MIXED'], description: 'Dominant direction of multi-timeframe confluence' },

    momentumShift: { category: 'ANALYTICSSUMMARY', name: 'momentumShift', icon: '🚀', path: 'analyticsSummary.mtfAnalysis_momentumShift', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'MODERATE', valueType: 'select', options: ['MODERATE', 'WEAK', 'STRONG'], description: 'Detected momentum shift strength' },
    absorption: { category: 'ANALYTICSSUMMARY', name: 'absorption', icon: '🧽', path: 'analyticsSummary.mtfAnalysis_absorption', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'false', valueType: 'select', options: ['true', 'false'], description: 'Indicates if order absorption is detected' },
    exhaustion: { category: 'ANALYTICSSUMMARY', name: 'exhaustion', icon: '🛑', path: 'analyticsSummary.mtfAnalysis_exhaustion', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'false', valueType: 'select', options: ['true', 'false'], description: 'Indicates if trend exhaustion is detected' },
    multiTFSignal: { category: 'ANALYTICSSUMMARY', name: 'multiTFSignal', icon: '⏱️', path: 'analyticsSummary.mtfAnalysis_multiTFSignal', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['NEUTRAL', 'LONG', 'SHORT'], description: 'Multi-timeframe aggregated signal direction' },
    multiTFConfidence: { category: 'ANALYTICSSUMMARY', name: 'multiTFConfidence', icon: '🎯', path: 'analyticsSummary.mtfAnalysis_multiTFConfidence', operators: ['>', '<'], defaultThreshold: 50, description: 'Confidence score of multi-timeframe signal' },

    volatility_volatilityRegime: { category: 'ANALYTICSSUMMARY', name: 'volatility_volatilityRegime', icon: '🌋', path: 'analyticsSummary.volatility_volatilityRegime', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NORMAL', valueType: 'select', options: ['LOW', 'NORMAL', 'HIGH', 'EXTREME'], description: 'Classified regime based on ATR percentile' },
    volatility_volTrend: { category: 'ANALYTICSSUMMARY', name: 'volatility_volTrend', icon: '📈', path: 'analyticsSummary.volatility_volTrend', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'STABLE', valueType: 'select', options: ['INCREASING', 'DECREASING', 'STABLE'], description: 'Detected trend of market volatility' },

    priceAction_nearestResistance: { category: 'ANALYTICSSUMMARY', name: 'priceAction_nearestResistance', icon: '🧱', path: 'analyticsSummary.priceAction_nearestResistance||null', operators: ['>', '<'], defaultThreshold: 50, description: 'Distance or value of nearest resistance level' },
    priceAction_nearestSupport: { category: 'ANALYTICSSUMMARY', name: 'priceAction_nearestSupport', icon: '🛡️', path: 'analyticsSummary.priceAction_nearestSupport||null', operators: ['>', '<'], defaultThreshold: 50, description: 'Distance or value of nearest support level' },

    funding_fundingDirection: { category: 'ANALYTICSSUMMARY', name: 'funding_fundingDirection', icon: '💸', path: 'analyticsSummary.funding_fundingDirection', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'LONGS_PAY', valueType: 'select', options: ['LONGS_PAY', 'SHORTS_PAY'], description: 'Funding rate direction (LONGS_PAY/SHORTS_PAY)' },
    funding_fundingLevel: { category: 'ANALYTICSSUMMARY', name: 'funding_fundingLevel', icon: '📊', path: 'analyticsSummary.funding_fundingLevel', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NORMAL', valueType: 'select', options: ['NORMAL', 'MODERATE', 'HIGH', 'EXTREME'], description: 'Funding rate level compared to historical norms' },
    funding_fundingPressure: { category: 'ANALYTICSSUMMARY', name: 'funding_fundingPressure', icon: '🗜️', path: 'analyticsSummary.funding_fundingPressure', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['NEUTRAL', 'LONGS_SQUEEZED', 'SHORTS_SQUEEZED'], description: 'Squeeze pressure based on funding rates' },
    funding_trend: { category: 'ANALYTICSSUMMARY', name: 'funding_trend', icon: '📈', path: 'analyticsSummary.funding_trend', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'STABLE', valueType: 'select', options: ['INCREASING', 'DECREASING', 'STABLE'], description: 'Detected trend of funding rates' },

    // correlation_classification: { category: 'ANALYTICSSUMMARY', name: 'correlation_classification', icon: '🔄', path: 'analyticsSummary.correlation_classification', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['NEUTRAL', 'HIGH_BETA_AGGRESSIVE', 'MARKET_TRACKER', 'LOW_BETA_DEFENSIVE', 'UNCORRELATED', 'NEGATIVE_BETA_HEDGE'], description: 'Beta-based correlation classification' },
    // correlation_betaReliability: { category: 'ANALYTICSSUMMARY', name: 'correlation_betaReliability', icon: '✅', path: 'analyticsSummary.correlation_betaReliability', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'RELIABLE', valueType: 'select', options: ['RELIABLE', 'UNRELIABLE'], description: 'Reliability flag for beta calculation' },

    vwap_vwap: { category: 'ANALYTICSSUMMARY', name: 'vwap_vwap', icon: '〽️', path: 'analyticsSummary.vwap_vwap', operators: ['>', '<'], defaultThreshold: 50, description: 'Volume Weighted Average Price (VWAP) relative position' },

    sorterMetrics_maxPain_direction: { category: 'ANALYTICSSUMMARY', name: 'sorterMetrics_maxPain_direction', icon: '🤕', path: 'analyticsSummary.sorterMetrics_maxPain_direction', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['LONG', 'SHORT', 'NEUTRAL'], description: 'Options max pain directional bias' },
    sorterMetrics_pcr_direction: { category: 'ANALYTICSSUMMARY', name: 'sorterMetrics_pcr_direction', icon: '⚖️', path: 'analyticsSummary.sorterMetrics_pcr_direction', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['LONG', 'SHORT', 'NEUTRAL'], description: 'Put/Call ratio directional bias' },
    sorterMetrics_macroPremium_direction: { category: 'ANALYTICSSUMMARY', name: 'sorterMetrics_macroPremium_direction', icon: '🌍', path: 'analyticsSummary.sorterMetrics_macroPremium_direction', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['LONG', 'SHORT', 'NEUTRAL'], description: 'Macro premium directional bias' },
    sorterMetrics_macroPremium_flowOrigin: { category: 'ANALYTICSSUMMARY', name: 'sorterMetrics_macroPremium_flowOrigin', icon: '🏛️', path: 'analyticsSummary.sorterMetrics_macroPremium_flowOrigin', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'MIXED', valueType: 'select', options: ['MIXED', 'US_INSTITUTIONAL_BUYING', 'US_RETAIL_BIDS', 'US_INSTITUTIONAL_SELLING', 'OFFSHORE_DOMINANCE'], description: 'Origin classification of order flow' },
    sorterMetrics_macroPremium_sentiment: { category: 'ANALYTICSSUMMARY', name: 'sorterMetrics_macroPremium_sentiment', icon: '🎭', path: 'analyticsSummary.sorterMetrics_macroPremium_sentiment', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['NEUTRAL', 'BULLISH', 'MILD_BULLISH', 'BEARISH', 'MILD_BEARISH'], description: 'Sentiment derived from macro premium' },

    sorterMetrics_pairs_divergence_normalizedScore: { category: 'ANALYTICSSUMMARY', name: 'sorterMetrics_pairs_divergence_normalizedScore', icon: '⚖️', path: 'analyticsSummary.sorterMetrics_pairs_divergence_normalizedScore', operators: ['>', '<'], defaultThreshold: 50, description: 'Normalized score for pairs divergence' },
    sorterMetrics_pairs_divergence_direction: { category: 'ANALYTICSSUMMARY', name: 'sorterMetrics_pairs_divergence_direction', icon: '↔️', path: 'analyticsSummary.sorterMetrics_pairs_divergence_direction', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['LONG', 'SHORT', 'NEUTRAL'], description: 'Pairs divergence signal direction' },
    toxicFlow_pairs_confidence: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_pairs_confidence', icon: '🎯', path: 'analyticsSummary.toxicFlow_pairs_confidence', operators: ['>', '<'], defaultThreshold: 50, description: 'Confidence level for toxic pairs flow' },

    toxicFlow_vpin_normalizedScore: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_vpin_normalizedScore', icon: '☠️', path: 'analyticsSummary.toxicFlow_vpin_normalizedScore', operators: ['>', '<'], defaultThreshold: 50, description: 'Normalized VPIN toxic flow score' },

    toxicFlow_vpin_direction: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_vpin_direction', icon: '↙️', path: 'analyticsSummary.toxicFlow_vpin_direction', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['LONG', 'SHORT', 'NEUTRAL'], description: 'Direction to reduce toxicity exposure' },

    toxicFlow_vpin_confidence: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_vpin_confidence', icon: '🎯', path: 'analyticsSummary.toxicFlow_vpin_confidence', operators: ['>', '<'], defaultThreshold: 50, description: 'Confidence level for VPIN signal' },

    toxicFlow_vpin_riskLevel: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_vpin_riskLevel', icon: '⚠️', path: 'analyticsSummary.toxicFlow_vpin_riskLevel', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NORMAL', valueType: 'select', options: ['NORMAL', 'EXTREME', 'HIGH', 'MODERATE'], description: 'Classified risk level for VPIN toxicity' },

    toxicFlow_vpin_toxicity: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_vpin_toxicity', icon: '☢️', path: 'analyticsSummary.toxicFlow_vpin_toxicity', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'MINIMAL', valueType: 'select', options: ['MINIMAL', 'SEVERE_TOXIC_FLOW', 'ELEVATED_TOXICITY', 'DETECTABLE_INSTITUTIONAL'], description: 'Categorized toxicity level' },
    toxicFlow_vpin_toxicity_direction: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_vpin_toxicity_direction', icon: '🕵️', path: 'analyticsSummary.toxicFlow_vpin_toxicity_direction', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'INFORMED_BUYING', valueType: 'select', options: ['INFORMED_BUYING', 'INFORMED_SELLING'], description: 'Informed buying or selling indicator' },
    toxicFlow_vpin_bucketImbalance: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_vpin_bucketImbalance', icon: '⚖️', path: 'analyticsSummary.toxicFlow_vpin_bucketImbalance', operators: ['>', '<'], defaultThreshold: 50, description: 'Imbalance percentage between buy/sell buckets' },


    toxicFlow_hawkes_normalizedScore: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_hawkes_normalizedScore', icon: '🦅', path: 'analyticsSummary.toxicFlow_hawkes_normalizedScore', operators: ['>', '<'], defaultThreshold: 50, description: 'Normalized Hawkes process toxic flow score' },

    toxicFlow_hawkes_direction: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_hawkes_direction', icon: '↙️', path: 'analyticsSummary.toxicFlow_hawkes_direction', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'NEUTRAL', valueType: 'select', options: ['LONG', 'SHORT', 'NEUTRAL'], description: 'Direction favored by Hawkes excitation' },
    toxicFlow_hawkes_confidence: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_hawkes_confidence', icon: '🎯', path: 'analyticsSummary.toxicFlow_hawkes_confidence', operators: ['>', '<'], defaultThreshold: 50, description: 'Confidence level for Hawkes signal' },

    toxicFlow_hawkes_lambda: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_hawkes_lambda', icon: 'λ', path: 'analyticsSummary.toxicFlow_hawkes_lambda', operators: ['>', '<'], defaultThreshold: 50, description: 'Current event intensity (Lambda)' },

    toxicFlow_hawkes_clusteringState: { category: 'ANALYTICSSUMMARY', name: 'toxicFlow_hawkes_clusteringState', icon: '🕸️', path: 'analyticsSummary.toxicFlow_hawkes_clusteringState', operators: ['==', '!=', 'CONTAINS'], defaultThreshold: 'STABLE', valueType: 'select', options: ['STABLE', 'EXTREME_EXCITATION', 'HERD_BEHAVIOR_ACTIVE', 'MILD_EXCITATION'], description: 'Clustering state of recent trades' }

};
